import { Strings } from './strings';
let fi: Strings =
    {
        addNewLayer: 'Lisää uusi taso',
        border: 'Reunat',
        borderRadius: 'Reunan säde(pyöreys)',
        cancel: 'Peruuta',
        chartDemoDescription: 'Tämä demo esittelee diagrammisymbolityypin käyttöä visualisoimalla Helsingin erilaisten ajoneuvojen jakaumaa piirakkadiagrammilla',
        chartType: 'Kuvaajan tyyppi',
        chartTypeDonut: 'Donitsidiagrammi',
        chartTypePie: 'Piirakkadiagrammi',
        chorodemoDescription: 'Tämä demo esittelee perinteisen koropleettikartan visualisoimalla Yhdysvaltojen asukastiheyden perusteella',
        clusterDemoDescription: 'Tämä demo esittelee klusteroidun kartan kuvaamalla HSL:n julkisen liikenteen kyytiinnousijat pysäkeittäin',
        clusterHelpText: 'Klusterointi on menetelmä karttapisteiden ryhmittelyyn, jolla parannetaan luettavuutta ja suorituskykyä kartoissa, joissa on runsaasti pisteitä',
        clusterInfo: 'Klusterien lisätiedot',
        clusterInfoHelpText: 'Valitse muuttuja listasta ja aseta sille tiedot, jotka näkyvät, kun hiiri on klusterin päällä',
        clusterMenuTitle: 'Klusterointi',
        clusterShowAvg: 'Näytä arvojen keskiarvo',
        clusterShowCount: 'Näytä pisteiden määrä',
        clusterShowSum: 'Näytä arvojen summa',
        clusterUseSymbolStyle: 'Käytä symbolin tyyliä',
        colorMenuStepHelp: 'Valitse kullekin askeleelle alaraja ja vastaava väri',
        colorMenuTitle: 'Värit',
        colorStepEquidistant: 'Samansuuruiset',
        colorStepKMeans: 'K-means',
        colorStepQuantiles: 'Kvantiilit',
        continue: 'Jatka',
        coordSystemHelp: 'Etkö ole varma? Testaa ensin oletusprojektiolla (WGS84) ja tarkista, ovatko kartan kohteet paikallaan',
        coordSystemMissing: 'Puuttuuko kaipaamasi koordinaattijärjestelmä? Hae Proj4-projektio palvelusta ',
        createNewFilter: 'Luo uusi suodatin',
        createNewMap: 'Luo uusi kartta',
        currentlySupportedTypes: 'Tuetut tiedostomuodot',
        customProjectionPrompt: 'Syötä oma Proj4-muotoinen projektioteksti',
        decimalAccuracy: 'Desimaalien määrä',
        deleteFilter: 'Poista suodatin',
        demoLoadButton: 'Avaa',
        displayText: 'Näyttöteksti',
        downloadMenuTitle: 'Lataus',
        downloadShowFilters: 'Näytä suodattimet kuvassa',
        downloadShowLegend: 'Näytä legenda kuvassa',
        editingLayerSelection: 'Valitse muokattava taso',
        editLayerProperties: 'Muokkaa tason ominaisuuksia',
        fileDetailsViewHeader: 'Vielä muutama yksityiskohta',
        fileTypeSupportInfo: 'Lisätietoa tuetuista tiedostomuodoista',
        fillColor: 'Täyttöväri',
        filterChangeOpacity: 'Muuta läpinäkyvyyttä',
        filterDragTip: 'Vinkki: raahaa suodatinta sen nimestä haluamaasi paikkaan kartalla',
        filterMenuTitle: 'Suodatus',
        filterRemove: 'Poista kartalta',
        filterUseDistinctValues: 'Käytä erillisiä arvoja',
        filterUseSteps: 'Määritä suodattimen askeleet',
        finishImport: 'Tee kartta!',
        giveNameToFilter: 'Anna suodattimelle nimi',
        giveNameToLayer: 'Anna tasolle nimi. Voit muokata tätä myös myöhemmin',
        heatDemoDescription: 'Tämä demo esittelee lämpökarttatyypin visualisoimalla HSL:n julkisen liikenteen kyytiinnousijat pysäkeittäin',
        heatLayers: 'Lämpökarttatasot',
        heatMapRadius: 'Lämpökartan solun halkaisija',
        icon: 'Ikoni',
        iconColorHelp: 'Voit muuttaa ikonien värejä Väriasetuksissa',
        iconField: 'Arvo, jonka perusteella ikoni valitaan',
        iconShape: 'Ikonin muoto',
        iconStepHelp: 'Aseta alaraja ja valitse vastaava ikoni',
        layerMenuDragDrop: 'Aseta uusi järjestys raahaamalla',
        layerMenuTitle: 'Tasot',
        layerType: 'Tason tyyppi',
        layerTypeHeat: 'Lämpökartta',
        layerTypeStandard: 'Normaali',
        legendAlignHorizontal: 'Aseta vaakatasoon',
        legendDistShow: 'Näytä arvojen jakauma',
        legendEditShow: 'Muokkaa selitteen tekstiä',
        legendMenuTitle: 'Selite',
        legendPosition: 'Sijainti ruudulla',
        legendTitle: 'Selitteen otsikko',
        legendVarShow: 'Näytä muuttujien nimet',
        loading: 'Ladataan...',
        maxBlockColumns: 'Maks. sarakkeita (leveys)',
        maxBlockRows: 'Maks. rivejä (korkeus)',
        name: 'Nimi',
        noFileNotification: 'Lataa tiedosto, joka ei ole tyhjä!',
        noHeadersError: 'Varmista että datasi sisältää asianmukaiset sarakkeiden nimet! Lue lisää projektin wikistä.',
        notification: 'Ilmoitus',
        opacity: 'Intensiteetti',
        openSavedMapButton: 'Avaa',
        or: 'Tai',
        popupClusterHelp: 'HUOM: klusterin tiedot avautuvat aina, kun hiiri on klusterin päällä',
        popupHelp: 'Tässä valikossa voit asettaa karttakohteille näkyviksi lisätietoja. Valitse muuttujat joiden arvot haluat näyttää, sekä lisätietojen avaustapa',
        popupMenuTitle: 'Pop-upit',
        previous: 'Edellinen',
        refreshMap: 'Päivitä kartta',
        revert: 'Käännä',
        saveAsFile: 'Lataa tiedostona',
        saveAsImage: 'Lataa kuvana',
        saveEmbedCode: 'Lataa upotuskoodi',
        saveFilter: 'Tallenna suodatin',
        selectBaseMap: 'Valitse pohjakartta',
        selectColorScheme: 'Valitse väriasteikko',
        selectColorVariable: 'Valitse värimuuttuja',
        selectCoordSystem: 'Valitse koordinaattijärjestelmä',
        selectFilter: 'Valitse muokattava suodatin',
        selectFilterLayer: 'Valitse suodatettava karttataso',
        selectFilterVariable: 'Muuta suodatinmuuttujaa',
        selectHeadersToShow: 'Valitse näytettävät muuttujat',
        selectLatHeader: 'Valitse pituus-/Y-koordinaattitiedon sarake',
        selectLayerPlaceholder: 'Valitse taso',
        selectLngHeader: 'Valitse leveys-/X-koordinaattitiedon sarake',
        selectPlaceholder: 'Valitse...',
        selectStepCalculationMode: 'Askelten laskumenetelmä',
        selectSymbolType: 'Valitse symbolin tyyppi',
        setCustomScheme: 'Määritä oma väriasteikko',
        setIcon: 'Valitse ikoni',
        showLegend: 'Näytä selite',
        showPopUpInPlace: 'Näytä elementin päällä',
        showPopupOnClick: 'Avaa lisätiedot klikkauksella',
        showPopUpOnHover: 'Avaa lisätiedot kun hiiri on karttakohteen päällä',
        showPopUpUpTop: 'Näytä kartan yläpuolella',
        singleBlockValue: 'Yhden ruudun arvo',
        singleBlockWidth: 'Yhden ruudun leveys',
        size: 'koko',
        sizeLowLimit: 'Koon alaraja (px)',
        sizeMultiplier: 'Koon kerroin',
        sizeUpLimit: 'Koon yläraja (px)',
        spreadsheets: 'taulukot',
        standardLayers: 'Normaalit tasot',
        steps: 'Askeleet',
        symboldemoDescription: 'Tämä demo esittelee MakeMapsin symbolivaihtoehtoja',
        symbolMenuChartTip: 'Vinkki: pidä kursoria diagrammin osan päällä nähdäksesi sen arvo',
        symbolMenuScale1: 'Skaalaa ',
        symbolMenuScale2: ' muuttujan perusteella',
        symbolMenuScaleHeight: 'Skaalaa korkeus muuttujan perusteella',
        symbolMenuTitle: 'Symbolit',
        symbolMenuUseFAIcon: 'Käytä muuta ikonia palvelusta ',
        symbolTypeBlocks: 'Ruudukko',
        symbolTypeChart: 'Diagrammi',
        symbolTypeSimple: 'Yksinkertainen',
        uploadDropBoxText: 'Pudota tiedosto tai klikkaa avataksesi tiedostovalikon',
        uploadMapDropBoxText: 'Pudota karttatiedosto tähän tai klikkaa avataksesi tiedostovalikon',
        uploadSavedMap: 'Lataa tallennettu kartta',
        uploadViewHeader: 'Lataa tiedosto järjestelmään',
        useClustering: 'Käytä klusterointia',
        useMultipleFillColors: 'Käytä useaa väriä',
        useMultipleIcons: 'Käytä useaa eri ikonia',
        welcomeAccessibility: 'Esteettömyys',
        welcomeAccessibilityText1: 'MakeMaps tarjoaa ',
        welcomeAccessibilityText2: ' -palvelusta erilaisia valmiita väriskaaloja , jotka soveltuvat myös näköhäiriöistä kärsiville lukijoille',
        welcomeDataFiltering: 'Datan suodatus',
        welcomeDataFilteringText: 'MakeMapsilla voit suodattaa dataa dynaamisesti. Voit määrittää askelluksen, käyttää yksittäisiä arvoja tai miten vain haluat ',
        welcomeFileSupport: 'Tiedostotuki',
        welcomeFileSupportLink: 'Kaikki tuetut tyypit',
        welcomeFileSupportText: 'MakeMaps tukee useita tiedostomuotoja, kuten XLSX,CSV,KML ja GPX.',
        welcomeOpenness: 'Avoimuus',
        welcomeOpennessText1: 'MakeMaps on avointa lähdekoodia, rakennettu avoimen lähdekoodin kirjastoja käyttäen, avointa dataa varten.',
        welcomeOpennessText2: 'Löydät meidät palvelusta ',
        welcomeUsability: 'Helppokäyttöisyys',
        welcomeUsabilityText1: 'MakeMapsilla voit tehdä näyttäviä ja helppolukuisia karttoja muutamalla klikkauksella. ',
        welcomeUsabilityText2: ' sisältää käyttöohjeita ja lisätietoa',
        width: 'leveys',
        wiki: 'Projektin Wiki',
    };

export { fi };
